.PHONY: build clean run

component_name := spring-webmvc-4.0.0
component_jar := spring-webmvc-4.0.0-1.0-SNAPSHOT.jar
plugin_name := spring-webmvc

build_command_module = -am -pl spring-webmvc/spring-webmvc-4.0.0

include ../../Makefile
