.PHONY: build clean run

component_name := akka-2.5.25
component_jar := akka-2.5.25-1.0-SNAPSHOT.jar
plugin_name := asynchttpclient

build_command_module = -am -pl akka/akka-2.5.25

include ../../Makefile

