.PHONY: build clean run

component_name := grizzly-http-client-1.15
component_jar := grizzly-http-client-1.15-1.0-SNAPSHOT.jar
plugin_name := grizzly-ahc

build_command_module = -am -pl grizzly-http-client/grizzly-http-client-1.15

include ../../Makefile
