.PHONY: build clean run

component_name := asynchttpclient-2.10.1
component_jar := asynchttpclient-2.10.1-1.0-SNAPSHOT.jar
plugin_name := asynchttpclient

include ../../Makefile

specialagent_jar_path := ${CURDIR}/../../$(specialagent_jar)

build_command_module = -am -pl asynchttpclient/asynchttpclient-2.10.1

build_command_start = cd ../.. &&
