.PHONY: build clean run

specialagent_jar := opentracing-specialagent-1.2.1-SNAPSHOT.jar
specialagent_jar_path := /Users/malafes/Downloads/${specialagent_jar}
component_name := jedis-3
component_jar := jedis-3-1.0-SNAPSHOT.jar
main_class := jedis3.App
plugin_name := jedis
