.PHONY: build clean run

component_name := lettuce-5.0.0
component_jar := lettuce-5.0.0-1.0-SNAPSHOT.jar
plugin_name := lettuce-5.0

build_command_module = -am -pl lettuce/lettuce-5.0.0

include ../../Makefile
