.PHONY: build clean run

component_name := spring-web/spring-web-5.0.0
component_jar := spring-web-5.0.0-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring-web/spring-web-5.0.0

include ../../Makefile
