.PHONY: build clean run

specialagent_jar := opentracing-specialagent-1.2.1-SNAPSHOT.jar
specialagent_jar_path := /Users/malafes/Downloads/${specialagent_jar}
component_name := jedis-2
component_jar := jedis-2-1.0-SNAPSHOT.jar
main_class := jedis2.App
plugin_name := jedis

include ../Makefile
