.PHONY: build clean run

component_name := spring-webmvc-3.2.18
component_jar := spring-webmvc-3.2.18-1.0-SNAPSHOT.jar
plugin_name := spring-webmvc

build_command_module = -am -pl spring-webmvc/spring-webmvc-3.2.18

include ../../Makefile
