.PHONY: build clean run

component_name := spring-webmvc-4.3.24
component_jar := spring-webmvc-4.3.24-1.0-SNAPSHOT.jar
plugin_name := spring:webmvc:4

build_command_module = -am -pl spring-webmvc/spring-webmvc-4.3.24

include ../../Makefile
