.PHONY: build clean run

component_name := kafka-1.1.0
component_jar := kafka-1.1.0-1.0-SNAPSHOT.jar
plugin_name := kafka-client

build_command_module = -am -pl kafka/kafka-1.1.0

include ../../Makefile
