sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2/repository

services:
  - cassandra
  - rabbitmq
  - docker

env:
  - TEST_SUITE=spring
  - TEST_SUITE=plain

install:
  # - wget -O opentracing-specialagent-1.3.3.jar "http://central.maven.org/maven2/io/opentracing/contrib/specialagent/opentracing-specialagent/1.3.3/opentracing-specialagent-1.3.3.jar"
  - wget -O opentracing-specialagent-1.3.5-SNAPSHOT.jar "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=1.3.5-SNAPSHOT&e=jar"

script:
  - ./test-${TEST_SUITE}.sh
