.PHONY: build clean run

specialagent_jar := opentracing-specialagent-1.2.1-SNAPSHOT.jar
specialagent_jar_path := /Users/malafes/Downloads/${specialagent_jar}
component_name := asynchttpclient
component_jar := asynchttpclient-1.0-SNAPSHOT.jar
main_class := asynchttpclient.App
plugin_name := asynchttpclient

include ../Makefile
