.PHONY: build clean run

component_name := thrift/thrift-0.12.0
component_jar := thrift-0.12.0-1.0-SNAPSHOT.jar
plugin_name := thrift

build_command_module = -am -pl thrift/thrift-0.12.0

include ../../Makefile
