.PHONY: build clean run

component_name := spring-web/spring-web-5.1.9
component_jar := spring-web-5.1.9-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring-web/spring-web-5.1.9

include ../../Makefile
