.PHONY: build clean run

component_name := cassandra-4.2.0
component_jar := cassandra-4.2.0-1.0-SNAPSHOT.jar
plugin_name := cassandra-driver

build_command_module = -am -pl cassandra/cassandra-4.2.0

include ../../Makefile
