.PHONY: build clean run

component_name := spring-web/spring-web-1.5.22
component_jar := spring-web-1.5.22-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring-web/spring-web-1.5.22

include ../../Makefile
