.PHONY: build clean run

component_name := servlet-sync
component_jar := servlet-sync-1.0-SNAPSHOT.jar
plugin_name := web-servlet-filter

build_command_module = -am -pl servlet/servlet-sync

include ../../Makefile

