.PHONY: build clean run

component_name := spring-scheduling-2.1.8
component_jar := spring-scheduling-2.1.8-1.0-SNAPSHOT.jar
plugin_name := spring-scheduling

build_command_module = -am -pl spring-scheduling/spring-scheduling-2.1.8

include ../../Makefile
