.PHONY: build clean run

component_name := spring-boot-kafka-2.1.8
component_jar := spring-boot-kafka-2.1.8-1.0-SNAPSHOT.jar
plugin_name := kafka-client

build_command_module = -am -pl spring-boot-kafka/spring-boot-kafka-2.1.8

include ../../Makefile
