.PHONY: build clean run

component_name := spring-web-3.2.18
component_jar := spring-web-3.2.18-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring-web/spring-web-3.2.18

include ../../Makefile
