.PHONY: build clean run

component_name := rxjava-2.1.0
component_jar := rxjava-2.1.0-1.0-SNAPSHOT.jar
plugin_name := rxjava-2

build_command_module = -am -pl rxjava/rxjava-2.1.0

include ../../Makefile
