.PHONY: build clean run

component_name := spring-web/spring-web-2.1.8
component_jar := spring-web-2.1.8-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring-web/spring-web-2.1.8

include ../../Makefile
