.PHONY: build clean run

component_name := spring-web-4.3.0
component_jar := spring-web-4.3.0-1.0-SNAPSHOT.jar
plugin_name := spring-web

build_command_module = -am -pl spring/spring-web-4.3.0

include ../../Makefile
