.PHONY: build clean run

component_name := httpclient-4.4
component_jar := httpclient-4.4-1.0-SNAPSHOT.jar
plugin_name := apache-httpclient

build_command_module = -am -pl httpclient/httpclient-4.4

include ../../Makefile
