.PHONY: build clean run

component_name := spring-websocket-2.1.8
component_jar := spring-websocket-2.1.8-1.0-SNAPSHOT.jar
plugin_name := spring-websocket

build_command_module = -am -pl spring-websocket/spring-websocket-2.1.8

include ../../Makefile
