.PHONY: build clean run

component_name := redisson-3.11.3
component_jar := redisson-3.11.3-1.0-SNAPSHOT.jar
plugin_name := redisson

build_command_module = -am -pl redisson/redisson-3.11.3

include ../../Makefile
