.PHONY: build clean run

component_name := spring-webmvc-1.5.22
component_jar := spring-webmvc-1.5.22-1.0-SNAPSHOT.jar
plugin_name := spring-webmvc

build_command_module = -am -pl spring-webmvc/spring-webmvc-1.5.22

include ../../Makefile
