.PHONY: build clean run

component_name := spring-boot-jms-2.1.8
component_jar := spring-boot-jms-2.1.8-1.0-SNAPSHOT.jar
plugin_name := spring-jms

build_command_module = -am -pl spring-boot-jms/spring-boot-jms-2.1.8

include ../../Makefile
