.PHONY: build clean run

component_name := spymemcached
component_jar := spymemcached-1.0-SNAPSHOT.jar
plugin_name := spymemcached

build_command_module_first = -am -pl spymemcached

include ../Makefile
