.PHONY: build clean run

component_name := spring-webmvc-2.1.8
component_jar := spring-webmvc-2.1.8-1.0-SNAPSHOT.jar
plugin_name := spring-webmvc

build_command_module = -am -pl spring-webmvc/spring-webmvc-2.1.8

include ../../Makefile
