.PHONY: build clean run

component_name := grizzly-http-server-2.4.4
component_jar := grizzly-http-server-2.4.4-1.0-SNAPSHOT.jar
plugin_name := grizzly-http-server

build_command_module = -am -pl grizzly-http-server/grizzly-http-server-2.4.4

include ../../Makefile
