.PHONY: build clean run

component_name := hazelcast-3.12.2
component_jar := hazelcast-3.12.2-1.0-SNAPSHOT.jar
plugin_name := hazelcast

build_command_module = -am -pl hazelcast/hazelcast-3.12.2

include ../../Makefile
