.PHONY: build clean run

component_name := mongo-async-3.11.0
component_jar := mongo-async-3.11.0-1.0-SNAPSHOT.jar
plugin_name := mongo-driver

build_command_module = -am -pl mongo/mongo-async-3.11.0

include ../../Makefile
