.PHONY: build clean run

component_name := mongo-reactive-1.8.0
component_jar := mongo-reactive-1.8.0-1.0-SNAPSHOT.jar
plugin_name := mongo-driver

build_command_module = -am -pl mongo/mongo-reactive-1.8.0

include ../../Makefile
