.PHONY: build clean run

component_name := mongo-3.9.0
component_jar := mongo-3.9.0-1.0-SNAPSHOT.jar
plugin_name := mongo-driver

build_command_module = -am -pl mongo/mongo-3.9.0

include ../../Makefile
