.PHONY: build clean run

specialagent_jar := opentracing-specialagent-1.2.1-SNAPSHOT.jar
specialagent_jar_path := /Users/malafes/Downloads/${specialagent_jar}
component_name := feign
component_jar := feign-1.0-SNAPSHOT.jar
main_class := feign.App

include ../Makefile
