.PHONY: build clean run

component_name := spring-webflux-2.1.0
component_jar := spring-webflux-2.1.0-1.0-SNAPSHOT.jar
plugin_name := spring-webflux

build_command_module = -am -pl spring-webflux/spring-webflux-2.1.0

include ../../Makefile
