.PHONY: build clean run

component_name := grizzly-http-client-1.16
component_jar := grizzly-http-client-1.16-1.0-SNAPSHOT.jar
plugin_name := grizzly-ahc

build_command_module = -am -pl grizzly-http-client/grizzly-http-client-1.16

include ../../Makefile
