.PHONY: build clean run

component_name := spring-scheduling-1.5.22
component_jar := spring-scheduling-1.5.22-1.0-SNAPSHOT.jar
plugin_name := spring-scheduling

build_command_module = -am -pl spring-scheduling/spring-scheduling-1.5.22

include ../../Makefile
