.PHONY: build clean run

component_name := lettuce-5.1.8
component_jar := lettuce-5.1.8-1.0-SNAPSHOT.jar
plugin_name := lettuce

build_command_module = -am -pl lettuce/lettuce-5.1.8

include ../../Makefile
