.PHONY: build clean run

component_name := reactor-3.3.0
component_jar := reactor-3.3.0-1.0-SNAPSHOT.jar
plugin_name := reactor

build_command_module = -am -pl reactor/reactor-3.3.0

include ../../Makefile

