.PHONY: build clean run

component_name := spring-boot-data-redis-1.5.22
component_jar := spring-boot-data-redis-1.5.22-1.0-SNAPSHOT.jar
plugin_name := jedis

build_command_module = -am -pl spring-boot-data-redis/spring-boot-data-redis-1.5.22

include ../../Makefile
