.PHONY: build clean run

component_name := reactor-3.2.3
component_jar := reactor-3.2.3-1.0-SNAPSHOT.jar
plugin_name := reactor

build_command_module = -am -pl reactor/reactor-3.2.3

include ../../Makefile

