.PHONY: build clean run

component_name := spring-boot-jms-1.5.22
component_jar := spring-boot-jms-1.5.22-1.0-SNAPSHOT.jar
plugin_name := spring-jms

build_command_module = -am -pl spring-boot-jms/spring-boot-jms-1.5.22

include ../../Makefile
