.PHONY: build clean run

specialagent_jar := /Users/malafes/Downloads/opentracing-specialagent-1.2.1-SNAPSHOT.jar

build:
	mvn clean package -DskipTests

clean:
	mvn clean

run:
	java \
		-Dls.componentName=spring-messaging \
		-Dls.collectorHost=collector.lightstep.com \
		-Dls.collectorProtocol=https \
		-Dls.collectorPort=443 \
		-Dls.accessToken=$(LS_TOKEN) \
		-Dsa.tracer=lightstep \
		-javaagent:$(specialagent_jar) -jar target/spring-messaging-1.0-SNAPSHOT.jar

run-local:
	java \
        -Dls.componentName=spring-cloud-messaging \
        -Dls.collectorHost=localhost \
        -Dls.collectorProtocol=http \
        -Dls.collectorPort=8360 \
        -Dls.accessToken=${LS_LOCAL_TOKEN} \
        -Dsa.tracer=lightstep \
        -javaagent:$(specialagent_jar) -jar target/spring-messaging-1.0-SNAPSHOT.jar

run-solo:
	java \
		-Dsa.tracer=mock \
		-Dsa.log.level=FINER \
		-Dsa.tracer.plugins.enable=false \
		-Dsa.instrumentation.plugins.enable=false \
		-Dsa.instrumentation.plugin.spring-messaging.enable=true \
		-javaagent:$(specialagent_jar) -jar target/spring-messaging-1.0-SNAPSHOT.jar

run-no-agent:
	java -jar target/spring-messaging-1.0-SNAPSHOT.jar