.PHONY: build clean run

component_name := spring-boot-data-redis-2.1.8
component_jar := spring-boot-data-redis-2.1.8-1.0-SNAPSHOT.jar
plugin_name := jedis

build_command_module = -am -pl spring-boot-data-redis/spring-boot-data-redis-2.1.8

include ../../Makefile
