.PHONY: build clean run

component_name := httpclient-4.5.9
component_jar := httpclient-4.5.9-1.0-SNAPSHOT.jar
plugin_name := apache-httpclient

build_command_module = -am -pl httpclient/httpclient-4.5.9

include ../../Makefile
