.PHONY: build clean run

component_name := asynchttpclient-2.7.0
component_jar := asynchttpclient-2.7.0-1.0-SNAPSHOT.jar
plugin_name := asynchttpclient

build_command_module = -am -pl asynchttpclient/asynchttpclient-2.7.0

include ../../Makefile

