.PHONY: build clean run

component_name := asynchttpclient
component_jar := asynchttpclient-2.7.0-1.0-SNAPSHOT.jar
plugin_name := asynchttpclient

include ../../Makefile

specialagent_jar_path := ${CURDIR}/../../$(specialagent_jar)
