.PHONY: build clean run

component_name := servlet-async
component_jar := servlet-async-1.0-SNAPSHOT.jar
plugin_name := web-servlet-filter

build_command_module = -am -pl servlet/servlet-async

include ../../Makefile

