.PHONY: build clean run

component_name := okhttp-3.14.2
component_jar := okhttp-3.14.2-1.0-SNAPSHOT.jar
plugin_name := okhttp

build_command_module = -am -pl okhttp/okhttp-3.14.2

include ../../Makefile
