.PHONY: build clean run

component_name := spring-webmvc-5.1.9
component_jar := spring-webmvc-5.1.9-1.0-SNAPSHOT.jar
plugin_name := spring-webmvc

build_command_module = -am -pl spring-webmvc/spring-webmvc-5.1.9

include ../../Makefile
