.PHONY: build clean run

component_name := cassandra-3.7.2
component_jar := cassandra-3.7.2-1.0-SNAPSHOT.jar
plugin_name := cassandra-driver

include ../../Makefile

specialagent_jar_path := ${CURDIR}/../../$(specialagent_jar)

