.PHONY: build clean run

component_name := cassandra-3.7.2
component_jar := cassandra-3.7.2-1.0-SNAPSHOT.jar
plugin_name := cassandra-driver

build_command_module = -am -pl cassandra/cassandra-3.7.2

include ../../Makefile
