.PHONY: build clean run

component_name := hystrix-1.5.18
component_jar := hystrix-1.5.18-1.0-SNAPSHOT.jar
plugin_name := hystrix

build_command_module = -am -pl hystrix/hystrix-1.5.18

include ../../Makefile


